apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/angelosha/devops-lab
    newTag: latest # CI rewrites this to the git sha on every deploy
