apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/angelosha/devops-lab
  newName: ghcr.io/angelosha/devops-lab
  newTag: ab1497b89b781db42c20737360f3b3b00fff8902
